# -*- coding: utf-8 -*-
"""EDA_MetaVerse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tbn1zl-WcYAcUQkprZBw9-H9Anm5IVKK
"""

import pandas as pd

# Load dataset
df = pd.read_csv("/content/metaverse_transactions_dataset.csv")

print(df.shape)
df.head()

import numpy as np

df["risk_score"] = pd.to_numeric(df["risk_score"], errors="coerce")

median_risk = df["risk_score"].median()
df["risk_score"] = df["risk_score"].fillna(median_risk)

risk_threshold = df["risk_score"].quantile(0.75)

df["is_high_risk_transaction"] = (df["risk_score"] >= risk_threshold).astype(int)

print(df["is_high_risk_transaction"].value_counts(normalize=True))

# Drop columns that directly encode the label
leakage_columns = [
    "risk_score",
    "risk_level",
    "anomaly_flag"
]

df = df.drop(columns=[col for col in leakage_columns if col in df.columns])

X = df.drop(columns=["is_high_risk_transaction"])
y = df["is_high_risk_transaction"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

# Identify categorical and numerical columns
categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()
numerical_cols = X.select_dtypes(exclude=["object"]).columns.tolist()

print("Categorical columns:", categorical_cols)
print("Numerical columns:", numerical_cols)

import numpy as np

fraud_ratio = y.mean()
print(f"Fraud percentage: {fraud_ratio * 100:.2f}%")

processed_df = pd.concat([X, y], axis=1)
processed_df.to_csv("processed_metaverse_transactions.csv", index=False)